spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username: root
spring.datasource.password: Misha06122000)))
spring.jpa.hibernate.ddl-auto: update
server.port: 8080
spring.jpa.show-sql: true
spring.jpa.properties.dialect: org.hibernate.dialect.MySQL8Dialect


indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru